#!/bin/sh

[ "$(cat /sys/class/net/wg*/operstate 2>/dev/null)" = "unknown" ] && wgIcon="G"

[ "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" = "up" ] && wifiIcon="W"

if [ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = "up" ]; then
	ethIcon="E"
else
	if [ ! $wifiIcon ]; then
		echo "N"
		exit 0
	fi
fi

[ "$(nmcli | grep VPN)" ] && vpnIcon="V" || vpnIcon=""
env printf '\x02'

RxTx="$(awk '
{
	if(l1){
		printf "RX:%.2f kB/s Tx:%.2f kB/s", ($2-l1)/1024, ($10-l2)/1024
	}
	else{
		l1=$2;
		l2=$10;
	}
}' \
	<(grep -E "^[we]" /proc/net/dev | head -n 1) \
	<(sleep 1; grep -E "^[we]" /proc/net/dev | head -n 1))"

echo "I:$wifiIcon$ethIcon$vpnIcon$wgIcon $RxTx"
